### ISSUE TITLE
0.6.0 release TODO list

### ISSUE THREAD

**Issue by jammees** [jammees/Rethink-Engine#2]
Create a documentation for the engine.

## Files to document:

- [x] Animation
- [x] Camera
- [x] Collision (Link)
- [x] Engine
- [x] Outline
- [x] Physics (Link)
- [x] Raycast (Link)
- [x] Scene
- [x] Settings
- [x] TaskDistributor
- [x] Template

## Features:

- [x] Add `ShouldFlush` symbol to `Scene` (previously DestroyAfterFlush)
- [x] Finish modding `Rigidbody` class to instead of destroying it's ui element, it should use `UiPool`
- [x] #3
- [x] Improve `.Flush` object deletion by adding each object a Janitor
- [x] #4 (Infinite recursion)

## Bugs:
- [x] Calling .Load and. .Flush constantly will somehow break the Compiler and will skip objects (in my case it was the empty object, found in Scenes\Test.lua)
- [x] Objects getting returned don't get their properties reset

**Comment by jammees** [comment]
Tought about improving the cleanup process in `.Flush` by adding a `Janitor` to each object added to scene.

This could improve the readability and modularity of the cleanup process:

**Comment by jammees** [comment]
Found couple of bugs while messing around:

- Calling .Load and. .Flush constantly will somehow break the Compiler and will skip objects (in my case it was the empty object, found in `Scenes\Test.lua`)
- Objects getting returned don't get their properties reset

**Comment by jammees** [comment]
Appearantly, ObjectPool was causing this annoying bug. I fixed it by adding a reset function to reset all of it's properties to default 👍 

Additionally, I optimized ObjectPool

**Comment by jammees** [comment]
ShouldFlush symbol has been implemented successfully! In case a full wipe is necessary an `ignoreShouldFlush` argument has been introduced to `.Flush()`

**Comment by jammees** [comment]
Progress report:

- Cleaned up the Compiler
- Better object data handling

*Took a small break, so that is why there is not a lot of things*

**Comment by jammees** [comment]
The 0.6.0 release will be delayed due to the editor.
Simply I thought releasing both together would be much better.

**Comment by jammees** [comment]
In #4 was mentioned that infinite recursion could solve the problem of more customizability. However there's no real reason to have a middleman between categories and objects.

Meaning, instead of having the structure: categories -> groups -> objects, the new format would be: category -> objects. Later down the line (probably v0.6.1) infinite recursion will be implemented.

**Comment by jammees** [comment]
Everything has been implemented and is complete.
